#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
CIGALE SED Plotting Tool
========================

This script generates a plot of the best-fit SED and the associated confidence
region (the "fan") from a CIGALE run. It uses the output from the
`export_python` module and can overplot the original photometric data for
comparison.

This provides a flexible, publication-quality alternative to the default
plots generated by the `sed_plot` module.

Prerequisites:
--------------
1. You must have run CIGALE with the `export_python` module activated in your
   `pcigale.ini` file. This creates a `<ID>_python_export.py` file for each
   object in your `out/` directory.
   
   Example `pcigale.ini` configuration:
   [analysis]
   analysis_modules = pdf_analysis, export_python

2. You need Python with the following libraries installed:
   - numpy
   - matplotlib
   - astropy

   You can install them with pip:
   `pip install numpy matplotlib astropy`

Usage:
------
The script is run from the command line.

Basic usage (plots the SED fan for a given object ID):
`python cigale_plot.py <OBJECT_ID>`

Full usage (with optional arguments):
`python cigale_plot.py <OBJECT_ID> --outdir /path/to/out/ --results /path/to/results.fits --save my_plot.pdf`

Arguments:
----------
- `object_id`: (Required) The ID of the object you want to plot. This must
               match the ID in your CIGALE input file.
- `--outdir`: (Optional) The path to the CIGALE output directory. 
              Defaults to './out/'.
- `--results`: (Optional) The path to the `results.fits` file. If provided,
               the script will overplot the observed photometric data points.
- `--save`: (Optional) The file path to save the plot (e.g., 'sed_plot.pdf').
            If not provided, the plot will be displayed on screen.

Example Command:
----------------
`python cigale_plot.py MyGalaxy_3 --results out/results.fits --save MyGalaxy_3_sed.pdf`

This command will:
1. Load the model data for 'MyGalaxy_3' from 'out/MyGalaxy_3_python_export.py'.
2. Load the observed photometry for 'MyGalaxy_3' from 'out/results.fits'.
3. Create a plot with the median SED, the 1-sigma confidence fan, and the
   observed data points.
4. Save the final plot to 'MyGalaxy_3_sed.pdf'.

"""

import numpy as np
import matplotlib.pyplot as plt
import importlib.util
import sys
import argparse
from pathlib import Path
from astropy.io import fits

def load_cigale_export_data(export_file_path):
    """Loads the SED grid data from a CIGALE python export file."""
    if not export_file_path.is_file():
        print(f"Error: CIGALE export file not found at {export_file_path}")
        print("Please ensure you have run CIGALE with the 'export_python' module.")
        sys.exit(1)
        
    spec = importlib.util.spec_from_file_location("cigale_export", export_file_path)
    cigale_data = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(cigale_data)
    return cigale_data.wavelengths, cigale_data.seds, cigale_data.likelihoods

def get_photometry(results_file, object_id):
    """Extracts observed photometry for a specific object from the results.fits file."""
    if not results_file.is_file():
        print(f"Warning: Results file not found at {results_file}. Cannot plot observed data.")
        return None, None, None

    with fits.open(results_file) as hdul:
        data = hdul[1].data
        
        # Find the row for the specific object
        try:
            obj_idx = np.where(data['id'] == object_id)[0][0]
            obj_data = data[obj_idx]
        except IndexError:
            print(f"Error: Object with ID '{object_id}' not found in {results_file}.")
            sys.exit(1)

        # Find all filter columns by looking for the wavelength columns ('_wl')
        filter_names = [col.replace('_wl', '') for col in data.columns.names if col.endswith('_wl')]
        
        waves, fluxes, errors = [], [], []
        for name in filter_names:
            # Check if the flux value is valid (not a nan or negative)
            if name in obj_data.columns.names and obj_data[name] > 0:
                waves.append(obj_data[f'{name}_wl'])
                fluxes.append(obj_data[name])
                errors.append(obj_data[f'{name}_err'])
                
    return np.array(waves), np.array(fluxes), np.array(errors)


def calculate_sed_percentiles(wavelengths, all_model_seds, likelihoods):
    """Calculates the probability-weighted 16th, 50th, and 84th percentiles of the SED."""
    # Convert likelihoods to probabilities
    probabilities = likelihoods / np.sum(likelihoods)
    
    n_wavelengths = len(wavelengths)
    p16_sed = np.zeros(n_wavelengths)
    p50_sed = np.zeros(n_wavelengths)
    p84_sed = np.zeros(n_wavelengths)

    print("Calculating weighted percentiles for the SED...")
    for i in range(n_wavelengths):
        # Get the flux of all models at this specific wavelength
        flux_slice = all_model_seds[:, i]
        
        # Sort the fluxes and the corresponding probabilities
        sort_indices = np.argsort(flux_slice)
        sorted_flux = flux_slice[sort_indices]
        sorted_prob = probabilities[sort_indices]
        
        # Calculate the cumulative probability (CDF)
        cdf = np.cumsum(sorted_prob)
        
        # Find the flux values at the 16th, 50th, and 84th percentiles
        p16_sed[i] = np.interp(0.16, cdf, sorted_flux)
        p50_sed[i] = np.interp(0.50, cdf, sorted_flux)
        p84_sed[i] = np.interp(0.84, cdf, sorted_flux)
        
    print("Calculation complete.")
    return p16_sed, p50_sed, p84_sed

def plot_sed(object_id, wavelengths, p16, p50, p84, obs_waves, obs_fluxes, obs_errors, save_path=None):
    """Generates and saves/shows the final SED plot."""
    fig, ax = plt.subplots(figsize=(10, 8))

    # Plot the median SED (50th percentile)
    ax.plot(wavelengths, p50, color='black', lw=2, label='Median Model (50%)', zorder=3)

    # Plot the "fan" for the 1-sigma region (16% to 84%)
    ax.fill_between(wavelengths, p16, p84, color='gray', alpha=0.5, label='16-84% Confidence Region', zorder=1)

    # Overplot observed photometry if available
    if obs_waves is not None and obs_fluxes is not None and obs_errors is not None:
        ax.errorbar(obs_waves, obs_fluxes, yerr=obs_errors, fmt='o', color='red', 
                    markersize=8, capsize=3, label='Observed Photometry', zorder=2)

    # Formatting the plot
    ax.set_xlabel('Rest-frame Wavelength (nm)', fontsize=14)
    ax.set_ylabel('Flux Density (mJy)', fontsize=14)
    ax.set_title(f'SED Posterior Distribution for {object_id}', fontsize=16)
    
    ax.set_xscale('log')
    ax.set_yscale('log')

    # Set plot limits to sensible values
    valid_p16 = p16[p16 > 0]
    min_y = np.min(valid_p16) / 5 if len(valid_p16) > 0 else 1e-3
    max_y = np.max(p84) * 5
    ax.set_xlim(1e2, 1e6)
    ax.set_ylim(min_y, max_y)

    ax.legend(fontsize=12)
    ax.grid(True, which='both', linestyle='--', linewidth=0.5)
    ax.tick_params(axis='both', which='major', labelsize=12)
    
    plt.tight_layout()

    if save_path:
        plt.savefig(save_path)
        print(f"Plot saved to {save_path}")
    else:
        plt.show()

def main():
    """Main function to parse arguments and run the plotting script."""
    parser = argparse.ArgumentParser(description="Plot CIGALE SEDs with confidence regions.")
    parser.add_argument("object_id", type=str, help="ID of the object to plot.")
    parser.add_argument("--outdir", type=str, default="out/", help="Path to the CIGALE output directory (default: ./out/).")
    parser.add_argument("--results", type=str, help="Path to results.fits file to plot observed photometry.")
    parser.add_argument("--save", type=str, help="File path to save the plot (e.g., 'sed.pdf'). Shows plot if not provided.")
    
    args = parser.parse_args()

    out_dir = Path(args.outdir)
    export_file = out_dir / f"{args.object_id}_python_export.py"
    
    # 1. Load model data from the export file
    wavelengths, seds, likelihoods = load_cigale_export_data(export_file)
    
    # 2. Load observed photometry if results file is provided
    obs_waves, obs_fluxes, obs_errors = None, None, None
    if args.results:
        results_file = Path(args.results)
        obs_waves, obs_fluxes, obs_errors = get_photometry(results_file, args.object_id)

    # 3. Calculate the SED percentiles
    p16, p50, p84 = calculate_sed_percentiles(wavelengths, seds, likelihoods)
    
    # 4. Generate the plot
    plot_sed(args.object_id, wavelengths, p16, p50, p84, obs_waves, obs_fluxes, obs_errors, args.save)

if __name__ == "__main__":
    main()
